//
// Autogenerated by Laurine - by Jiri Trecak ( http://jiritrecak.com, @jiritrecak )
// Do not change this file manually!
//


// --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
// MARK: - Imports

import Foundation


// --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
// MARK: - Localizations


public struct Localizations {


  public struct SelectLanguage {

    /// Base translation: Select language
    public static var Title : String { return localized(string: "select-language.title", tableName: nil, bundle: Bundle.main, value: "", comment: "") }

  }

  public struct News {

    /// Base translation: News
    public static var Title : String { return localized(string: "news.title", tableName: nil, bundle: Bundle.main, value: "", comment: "") }

    /// Base translation: %i minutes ago
    public static func TimeTitle(value1 : Int) -> String {
      return String(format: localized(string: "news.time-title", tableName: nil, bundle: Bundle.main, value: "", comment: ""), value1)
    }

  }
}